name: Auto Assign and Review

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewer-and-assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Assign and request review
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: kinoko2k
